[feature/#211] 동아리 활동 API 구현
InhaBas/Inhabas.com-api pull request #224
Opened 2024-01-26 02:18 UTC by whitem4rk

1. s3 filestorage 연결 
[https://s3.console.aws.amazon.com/s3/buckets/inhabas-bucket?region=ap-northeast-2&bucketType=general&tab=objects]

2. BaseEntity -> BaseBoard -> 특정 board 처럼 상속 받아서 처리함. DB는 BaseBoard로 모든 글의 공통 정보를 저장하는 **baseboard table이 있고 특정 board 마다 table이 또 존재.** 
baseboard를 사용하지 않고 각각의 board마다 별도의 연결되어있지 않은 table로 관리하려 했는데 이는 댓글 관리에서 너무 많은 중복코드를 유발합니다. 현재 게시판의 종류가 굉장히 많은 이 서비스에서 board마다 댓글 endpoint를 만든다면 최소 4(CRUD) * 10(게시판 최소 개수) 가 발생합니다. 모든 댓글 서비스는 동일한 로직으로 동작하므로 BaseBoard 하나만 참조해서 댓글을 불러 올 수 있도록 하였습니다. 다만 게시판 별로 요구 권한이 다르므로 이를 꼼꼼하게 처리할 필요가 있습니다.

3. security config에서의 인가, 인증 규칙이 명확하지 않고 정리되어 있지 않다고 느낍니다. 추후에 수정이 필요해 보입니다.

여러가지 권한이 꼬여있는데 부족한 실력으로 설계를 하려고 하니 코드 가독성이나 구조의 깔끔성이 많이 떨어집니다. 개인적인 구두 설명 없이 코드만 읽고 이해하기에는 한계가 있으니 자유롭게 로직에 대한 설명을 요구하면 됩니다. 더 좋은 방안이 떠오르면 언제든지 제시해주시기 바랍니다.

2024-01-28 05:39 UTC, skytin1004 requested changes
@whitem4rk 시간날 때 리뷰 확인 부탁드립니다!

2024-01-28 05:39 UTC, skytin1004 commented on resource-server/src/test/java/com/inhabas/api/domain/comment/repository/CommentRepositoryTest.java
> +        assertThat(all.size()).isEqualTo(0);
`assertThat(all).hasSize(0)`

2024-01-28 05:39 UTC, skytin1004 commented on resource-server/src/test/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImplTest.java
> +        assertThat(clubActivityDtoList.size()).isEqualTo(1);
`assertThat(clubActivityDtoList).hasSize(1)`

2024-01-28 05:39 UTC, skytin1004 commented on resource-server/src/test/java/com/inhabas/api/domain/comment/usecase/CommentServiceTest.java
> +        assertDoesNotThrow(() -> commentService.delete(1L));
```
import static org.assertj.core.api.Assertions.assertThatCode;

assertThatCode(() -> commentService.delete(1L))
    .doesNotThrowAnyException();
```

2024-01-28 05:39 UTC, skytin1004 commented on module-auth/src/test/java/com/inhabas/api/auth/domain/token/JwtTokenResolverTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
```
import org.assertj.core.api.Assertions;
```

에서 이미 import가 되어있는데 또 import가 된 것 같습니다.

2024-01-28 05:39 UTC, skytin1004 commented on resource-server/src/test/resources/application.yml
> +            client-id: 1c53a2cc424b53b72d06803dbdf3f374
client-id 및 client-secret이 직접 노출되도록 설정되어있는데, 보안 문제 관련해서 확인 부탁드리겠습니다.
가능하면 ${IBAS_DEV_KAKAO_CLIENT_ID} 환경변수 이용하는게 더 좋아보입니다!

2024-01-28 07:50 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImpl.java
> +
`@Transactional`과 `try catch`문을 같이 쓰면 안되는 경우는 발생된 exception이 catch에 의해 처리되어 `@Transactional`에 의한 트랜잭션 처리 루틴으로 예외는 전파되지 않는 경우입니다.

제가 `try catch`를 굳이 넣었던 이유는 DB의 롤백과 File storage의 롤백을 둘 다 처리하려고 했기 때문입니다. 예를 들면

> DB에 파일정보가 저장된 후, file storage에 저장하는 과정에서 에러가 발생한 경우

file storage, db 모두 롤백이 되어야 하지만 `@Transactional` 만으로는 file storage 롤백은 발생하지 않습니다. 



하지만 코드를 자세히 보니 제 의도와는 다르게 문제점이 있음을 발견했습니다.
1. file 저장 예외 발생 시 보상 로직 부재
2. 트랙잭션 관련 코드가 `try catch`문에 포함되어있다는 점

```java
    @Transactional
    public void updateClubActivity(Long boardId, SaveClubActivityDto saveClubActivityDto) {

        AlbumBoard clubActivity = clubActivityRepository.findById(boardId).orElseThrow(NotFoundException::new);
        List<BoardFile> updateFiles = new ArrayList<>();

        if (saveClubActivityDto.getFiles() != null) {
            clubActivity.updateText(saveClubActivityDto.getTitle(), saveClubActivityDto.getContent());
            try {
                updateFiles = saveClubActivityDto.getFiles().stream().map(file -> {
                    String url = s3Service.uploadS3File(file, generateRandomUrl());
                    return BoardFile.builder()
                            .name(file.getOriginalFilename())
                            .url(url)
                            .board(clubActivity)
                            .build();
                }).collect(Collectors.toList());

            } catch (Exception e) {
                for (BoardFile boardFile : updateFiles) {
                    s3Service.deleteS3File(boardFile.getUrl());
                }
                throw new S3UploadFailedException();
            }
        }

        clubActivity.updateFiles(updateFiles);

    }
```


DB 로직과 `try catch`를 분리했고 `try catch`에서 exception이 발생했을때 `S3UploadFailedException`를 throw하여 `@Transactional`이 올바르게 동작하도록 하였습니다.

2024-01-28 14:05 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImpl.java
> +    @Transactional(readOnly = true)
고려를 안한건 아니었는데 무슨 이유로 포기했던걸로 기억합니다. 더 나은 방법이 된다면 개선하도록 하겠습니다.

2024-01-29 01:44 UTC, skytin1004 commented on resource-server/src/main/java/com/inhabas/api/domain/club/usecase/ClubActivityServiceImpl.java
> +    @Transactional(readOnly = true)
알려주셔서 감사합니다!

2024-01-29 01:56 UTC, skytin1004 approved these changes
@whitem4rk  이상 없습니다. 머지 하겠습니다!

2024-01-29 01:58 UTC, merged

2024-01-29 02:30 UTC, skytin1004 commented on resource-server/src/test/resources/application.yml
> +            client-id: 1c53a2cc424b53b72d06803dbdf3f374
시크릿 키 재발급 진행