Tester
InhaBas/Inhabas.com-api pull request #249
Opened 2024-03-11 14:29 UTC by skytin1004

프로젝트 게시판 API 구현, ./ gradlew clean build 성공 확인했습니다.

2024-03-14 02:39 UTC, whitem4rk requested changes

2024-03-14 02:39 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/domain/project/domain/PinOption.java
> +
`PinOption`파일이 2개 존재합니다.

2024-03-14 02:39 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/domain/project/domain/ProjectBoard.java
> +@Table(name = "NORMAL_BOARD")
테이블명을 다르게 설정해서 DB에 새로운 테이블이 생성되도록 해주세요. 그리고 프로젝트 글을 생성했을때 db에 데이터가 잘 들어오는지도 확인해주세요.

2024-03-14 02:39 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/domain/project/usecase/ProjectBoardServiceImpl.java
> +@RequiredArgsConstructor
`@Transactional` 을 메서드 별로 지정해주세요. 쓰기 기능이 없는경우 `readOnly=True` 설정을 해주세요.

2024-03-14 02:39 UTC, whitem4rk commented on resource-server/src/test/java/com/inhabas/api/web/ProjectBoardControllerTest.java
> +  @DisplayName("게시판 종류 당 글 개수 조회 성공 200")
`게시판` 을 `프로젝트` 로 수정해주세요.

2024-03-14 02:39 UTC, whitem4rk commented on resource-server/src/main/java/com/inhabas/api/web/ProjectBoardController.java
> +@Tag(name = "게시글 관리")
`프로젝트` 로 수정해주세요. `project` 폴더 내에 코드들이 `게시판` 으로 명세된게 많은데 일괄 수정해주세요.

2024-03-15 09:26 UTC, skytin1004 commented
@whitem4rk  리뷰 반영 완료했습니다. 시간 날 때 리뷰 부탁드리겠습니다.

2024-03-16 14:22 UTC, whitem4rk approved these changes

2024-03-16 14:24 UTC, merged