[Feature/#25]  Board Detail, BoardList Dto 생성
InhaBas/Inhabas.com-api pull request #29
Opened 2022-01-18 05:26 UTC by MingyeomKim

2022-01-18 09:53 UTC, Dong-Hyeon-Yu requested changes
저녁 먹고 와서 
같이 얘기해봅시다~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/BoardDetailDto.java
> +    private String title;
`Bean Validation` 는 `controller` 로 파라미터가 넘어올때에 시행됩니다
`BoardDetailDto` 는 response 전용이니까 `validation` 을 거치지 않습니다~ 
또 생성이나 수정 시에 유효성 검증을 하고 난 후에 저장됩니다~
따라서 `presentation` 전용 `dto`는 `validation` 에 관한 `annatation` 붙이지 않아도 됩니다~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/BoardDetailDto.java
> +    private String title;
작성자에 대한 필드도 필요해요~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/BoardListDto.java
> +    private LocalDate updated;
BoardDetailDto 와 같은 맥락으로 유효성 검사가 필요 없습니다~!
boar그리고 좋은 생각이 났는데,
BoardDetailDto 의 contents를 empty string 으로 반환하면 BoardListDto와 같은 의미인듯?
그러면 BoardListDto 없어도 되지 않을까요??

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/SaveBoardDto.java
> +    private Integer category_id;
자바 코드 컨벤션 => CamelCase 권장!!
```suggestion
    @NotNull
    private Integer categoryId;
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/SaveBoardDto.java
> +@NoArgsConstructor
필요없으면 지워주세요~~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/UpdateBoardDto.java
> +@NoArgsConstructor
요기도~~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/dto/board/UpdateBoardDto.java
> +    private Integer category_id;
요기도~~
```suggestion
    private Integer categoryId;
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/service/board/BoardService.java
> +    Optional<NormalBoard> getBoard(String category, Integer board_id);
요기도~~
```suggestion
    Optional<NormalBoard> getBoard(Integer categoryId, Integer boardId);
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/service/board/BoardServiceImpl.java
> +            return boardRepository.save(updateBoardDto.toEntity());
중복되는 연산은 피해주세요~
```java
    @Override
    public NormalBoard update(UpdateBoardDto updateBoardDto) {
        NormalBoard entity = updateBoardDto.toEntity();
        if(DoesExistBoard(entity)){
            return boardRepository.save(entity);
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/service/board/BoardServiceImpl.java
> +    }
추후에 page 객체 이용해서 pagenation 기능 적용해야합니다~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/test/java/com/inhabas/api/dto/board/SaveBoardDtoTest.java
> +        assertFalse(violations.isEmpty());
이런 식으로 어떤 오류가 났는지를 테스트하면 더 좋을 거같아요~
```java
assertEquals(1, violations.size());  // ConstraintViolation에 실패에 대한 정보가 담긴다.
assertEquals("must not be null", violations.iterator().next().getMessage());
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/test/java/com/inhabas/api/dto/board/UpdateBoardDtoTest.java
> +    public void UpdateBoardDto_is_OK() {
validation 의 목적은 잘못 입력된 정보를 올바르게 처리하기 위함이죠?
정상적인 입력에 대해서 dto를 잘 생성해야겠지만
잘못된 입력을 잘 검증할 수 있는지를 테스트하는 것도 필요합니다~

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/controller/BoardController.java
> +    public NormalBoard board(@RequestParam String category, @RequestParam Integer board_id) {
```suggestion
    public NormalBoard board(@RequestParam Integer category, @RequestParam Integer boardId) {
```

2022-01-18 09:53 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/controller/BoardController.java
>      private final NormalBoardRepository repository;
repository는 여기서 사용하지 않는게 더 좋아보여요~
Service 에서 UseCase 를 충분히 정의하기 때문에 service 를 잘 활용하는 것이 좋을거같네요!

2022-01-19 12:03 UTC, Dong-Hyeon-Yu approved these changes
고생했어요~~
컨트롤러랑 서비스는 일단 진행중인거죠?
머지 시키고, 레파지토리 수정해서 PR 올릴게요~~!

2022-01-19 12:09 UTC, merged

2022-01-20 04:58 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/controller/BoardController.java
> +        return boardService.write(saveBoardDto);
Integer 반환하는 걸로 수정했습니당