[Feature/#56] 공모전 게시판 CRUD
InhaBas/Inhabas.com-api pull request #57
Opened 2022-02-03 18:43 UTC by MingyeomKim

테스트 코드 미작성하였습니다 😥

2022-02-04 11:26 UTC, Dong-Hyeon-Yu requested changes
오 굳굳 신속 정확하게 잘 했네요~~ :+1: 
좋습니다~~ 한번에 올라온 코드가 많다보니 자잘한 의견이 좀 많아요~
수정사항 큰 건 없으니까 조금 수정만 부탁드리구요 :pray: :sweat_smile: 

테스트 2가지만 추가했으면 좋겠어요!
- queryDsl 로 작성한 repository 로직은 테스트 코드 작성하는게 좋을 거 같아요~ 

- 그 Bean Validation 테스트는 controller나 dto 테스트 둘 중 하나에서 하면 될 듯 한데, 
살짝 귀찮은 감이 없지 않으니까, 필드 하나하나 테스트 작성하지 말고,
  1. 전부 null 일 경우 
  2. 전부 blank 일 경우
  3. 전부 길이 제한 넘길 경우 

  등등 으로 경우의 수를 나눠서 필드들을 한꺼번에 테스트하면 될듯요!
validation 후에는 모든 오류메세지가 한번에 묶여 나오니까 이렇게 하면 편할듯요??
  ```java
  assertThat(errorMessage).contains("제목은 뭐시기", "내용은 뭐시기 저시기") 
  ```

전체적으로 잘했네용 허허 :smiley: :+1:  
마무리만 잘 부탁할게요~

2022-02-04 11:26 UTC, Dong-Hyeon-Yu commented on src/test/java/com/inhabas/api/dto/contest/BaseContestBoardDtoTest.java
> +            , LocalDate.of(2022, 01, 01), LocalDate.of(2022, 01,26) , 12201863);
요건 사용안한거죠?? 

요렇게 해도 좋은데, 그대로 사용하게 된다면 치명적인 문제가 발생할 있어요!! 
~(경험담인건 안비밀.. 지금 멤버쪽도 그렇게 되어있을텐데 허허)~

static final 이면 테스트 간 `공유변수`로 사용됩니다~ 
테스트 간에는 독립성이 보장되어야 하는데, 이 공유 변수들 때문에 독립성이 보장되지 않는 경우가 있죠!
아마 jpa 관련 test 하다가 그랬던거 같은데 
테스트 간 같은 영속 컨텍스트를 참조하면서 문제가 발생했던 기억이 있네요! 
그래서 `NormalBoardTest` 보면 매번 새로운 인스턴스를 생성하는 팩토리 매소드로 작성되어 있을 거에요! 
이거 때문에 좀 고생했었거든요~
이렇게 사용할거면 참고하라고 남겨놓아요~~ (클래스 이름 수정해주세용~)

2022-02-04 14:13 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/dto/board/BoardDto.java
>      @JsonFormat(shape = JsonFormat.Shape.STRING, pattern="yyy-MM-dd'T'HH:mm:ss.SSS")
신기하게도 년도가 잘 나오네요 🤔
yyyy가 공식적인 표현이니 수정하겠습니다!

2022-02-04 14:26 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        contestBoard.writtenBy(writer);
저 여기서 의문점이 있었는데, 저렇게 반환된 인스턴스에 바로 writtenBy를 붙이면 
![image](https://user-images.githubusercontent.com/67851124/152545310-c5b4a73d-b456-46ac-8dab-c41bf5852710.png)
이렇게 에러가 뜨더라구요

그런데 객체 따로 빼서 
```
contestBoard.writtenBy(writer);
```
이렇게 작성하면 오류가 안 생겨서 일단 저렇게 작성해놓았습니다 !

2022-02-04 15:19 UTC, MingyeomKim commented on src/test/java/com/inhabas/api/dto/contest/BaseContestBoardDtoTest.java
> +            , LocalDate.of(2022, 01, 01), LocalDate.of(2022, 01,26) , 12201863);
경험에 의한 조언 감사합니다 👍

2022-02-05 05:41 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        entity.setDeadline(dto.getDeadline());
setter의 반환값이 없어서 저렇게 연쇄적으로 작성하는 코드는 불가한 것 같습니다 🥺

2022-02-05 07:10 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        contestBoard.writtenBy(writer);
아니면 `NormalBoard` 내부에서 
멤버와 실제로 연관관계를 맺는 함수는 따로 `protected void _writtenby(writer)` 이렇게 만들어 놓고 
실제 public writtenBy 에서는  `super._writtenby(writer)` 를 호출하고 자신을 리턴하는거죠! 더 일관성있는 방법인거 같기도 하고??

2022-02-05 07:10 UTC, Dong-Hyeon-Yu commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        entity.setDeadline(dto.getDeadline());
그래서 setter 의 리턴값을 엔티티로 변경한 후에 저렇게 사용하는건 어떨지를 물어본거에요!
그렇게 되면 사실 생성자+빌더를 사용하는 거랑 별로 다르지 않아서, 
그냥 생성자로 엔티티를 새로 만들어서 save 해도 될거같고?

2022-02-05 09:17 UTC, MingyeomKim commented on src/test/java/com/inhabas/api/service/ContestBoardServiceTest.java
> +        //given
테스트 해본 결과, 정렬이 잘 되어서 출력되지 않았습니당
원인은 findAllByMenuId 를 given 메서드로 Mocking하여서 
```
        given(contestBoardRepository.findAllByMenuId(any(), any())).willReturn(expectedContestBoardDto);

```
queryDsl를 거치지 못해 페이징, 정렬을 거친 객체가 expectedContestBoardDto에 담기지 못한거라고 생각했습니다.
```
        Page<ListContestBoardDto> expectedContestBoardDto = new PageImpl<>(results, pageable, results.size());
```

해결방안은 더 생각해본 다음에 추가로 코멘트 달겠습니다!

2022-02-05 14:24 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        contestBoard.writtenBy(writer);
```
    protected void _writtenBy(Member writer){
        if (Objects.isNull(this.writer))
            this.writer = writer;
        else
            throw new IllegalStateException("게시글 작성자를 수정할 수 없습니다.");
    }

    public NormalBoard writtenBy(Member writer){
        this._writtenBy(writer);
        return this;
    }
```

NormalBoard는 위와 같이 수정하고  ContestBoard에 _writtenBy를 호출하는 방식으로 작성하였습니다!
```
    public ContestBoard writtenBy(Member writer){
        super._writtenBy(writer);
        return this;
    }
```

2022-02-05 15:31 UTC, MingyeomKim commented on src/main/java/com/inhabas/api/service/contest/ContestBoardServiceImpl.java
> +        entity.setDeadline(dto.getDeadline());
생성자, 혹은 빌더 패턴을 이용해서 객체를 새로 생성하고, Id 포함해서 초기화하는 방식으로 update 수정했습니다. Entity와 Dto의 Setter은 모두 지웠습니다!

```java
 @Override
    public Integer update(UpdateContestBoardDto dto) {
        ContestBoard entity = ContestBoard.builder()
                .id(dto.getId())
                .title(dto.getTitle())
                .contents(dto.getContents())
                .association(dto.getAssociation())
                .topic(dto.getTopic())
                .start(dto.getStart())
                .deadline(dto.getDeadline())
                .build();
        // em.merge() 호출되는 지 확인할 것
        return contestBoardRepository.save(entity).getId();
    }
```

2022-02-07 09:25 UTC, Dong-Hyeon-Yu approved these changes
굳굳 마무리 잘 해주었네요~~ 고마워요~ 😄

2022-02-07 09:26 UTC, merged